---
roles:
  - name: geerlingguy.swap
    version: "1.2.0"

collections:
  - name: community.general
  - name: community.crypto
  - name: community.docker
  - name: community.digitalocean
  - name: ansible.posix
