---
do_droplet:
  config:
    sshd_port: 22
  specs:
    name_prefix: "{{ training_prefix }}"
    size: s-1vcpu-1gb
    region: lon1
    image: ubuntu-24-10-x64
    project_name: "Training"
    tags:
      - "{{ training_prefix }}"
      - training
