---
do_droplet:
  specs:
    name_prefix: "{{ training_prefix }}"
    size: s-1vcpu-1gb
    region: lon1
    image: ubuntu-23-10-x64
    project_name: "PloneConference2023"
    tags:
      - "{{ training_prefix }}"
      - training
